### ISSUE TITLE
FR-001: Provide process-level topology without relying on eBPF

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowys/deepflow#1481]
# Description

Mixed deployment of different services on cloud hosts is very common. When the kernel cannot provide eBPF capabilities, it is desirable to associate all data with process names.

# Use Case

At Xiaomi, we deploy different services on the same cloud host. If a process-level service topology can be provided, business teams can quickly implement application observability without complex code instrumentation.

**Comment by sharang** [comment]
Solution: 

First, the process information on the host is collected through the agent (the collection range can be limited by os_proc_regex configuration), and the server generates a global global-process-id for each process after summarizing. Secondly, the current socket list is exchanged between agents through the server, so that all agents can mark the correct global-process-id for both ends of cBPF data. Finally, all data tables in the flow-metrics and flow-log libraries add a gpid field and support association to process-name.

In addition, through the static_config.os_app_tag_exec configuration, the agent can execute a specified CLI command to obtain the service tag information corresponding to the process ID, which will be associated with the gpid and support query through the queryer API.

**Comment by sharang** [comment]
cc @mytting @liqian1834
