### ISSUE TITLE
agent watch k8s error

### ISSUE THREAD

**Issue by BruceChinese** [deepflowys/deepflow#950]
tencent cloud tke cluster:

![image](https://user-images.githubusercontent.com/12492229/192506506-690ccc63-7bb1-420a-849e-5a93595089de.png)

agent watch error

**Comment by sharang** [comment]
@BruceChinese We also just found out that the certificate of the TKE cluster is invalid. We opened a ticket and asked Tencent Cloud, and we are waiting for a reply.

In order to bypass this problem, since we only watch resource information inside the cluster, the correctness check of the certificate has been ignored in the latest deepflow-agent. You can try to upgrade

**Comment by sharang** [comment]
When we checked in the TKE environment, we found that the communication between the Pod and the apiserver will go through a Layer7 LoadBalancer, and we also observed that the LB log had an error calling TKE credentials.

![image](https://user-images.githubusercontent.com/1598518/192665388-d5c4d878-8b28-488d-984f-1edd5ba55709.png)

**Comment by BruceChinese** [comment]
目前升级agent到latest 并且清除数据重新部署后ok了
